version: '2'

services:
    php:
        build: ./${PHP_VERSION}
        container_name: ${PROJECT_NAME}php
        volumes_from:
            - source
        ports:
            - '${INTERFACE}:9000:9000'
        links:
            - mariadb
            - memcached
        networks:
            - bitrixdev
        restart: always
    web_server:
        build: ./${WEB_SERVER_TYPE}
        container_name: ${PROJECT_NAME}webserver
        depends_on:
            - source
        volumes_from:
            - source
        ports:
            - '${INTERFACE}:80:80'
            - '${INTERFACE}:443:443'
        links:
            - php
        networks: 
            - bitrixdev
        restart: always
    mariadb:
        build: ./mariadb
        container_name: ${PROJECT_NAME}mariadb
        volumes:
            - mysql:/var/lib/mariadb
        ports:
            - '${INTERFACE}:3306:3306'
        environment:
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        networks:
            - bitrixdev
        restart: always
    memcached:
        image: memcached:1.5-alpine
        container_name: ${PROJECT_NAME}memcached
        volumes_from:
            - source
        ports:
            - '${INTERFACE}:11211:11211'
        networks:
            - bitrixdev
        restart: always
    source:
        image: alpine:latest
        container_name: ${PROJECT_NAME}source
        volumes:
            - ./logs/${WEB_SERVER_TYPE}:/var/log/${WEB_SERVER_TYPE}
            - ./logs/php:/var/log/php
            - ./logs/mysql:/var/log/mysql
            - ./logs/memcached:/var/log/memcached
            - ./data/mysql:/var/lib/mysql
            - ./data/memcached:/var/lib/memcached
            - ./www/html:/var/www/html
        networks:
            - bitrixdev
networks:
    bitrixdev:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: ${IPV4}/24
volumes:
    mysql: